
import { User, UserRole, ChargingPoint, ChargerType, Booking, BookingStatus } from './types';

export const mockUser: User = {
  id: 'user-1',
  name: 'Catalina Rojas',
  email: 'catalina.rojas@example.com',
  avatarUrl: 'https://picsum.photos/seed/catalina/100/100',
  roles: [UserRole.Driver, UserRole.Host],
};

export const mockChargers: ChargingPoint[] = [
  {
    id: 'charger-1',
    hostId: 'user-1',
    name: 'Cargador Rápido Las Condes',
    address: 'Av. Apoquindo 5000, Las Condes, Santiago',
    lat: -33.414,
    lng: -70.57,
    chargerType: ChargerType.CCS,
    pricePerHour: 5500,
    availability: [
      { dayOfWeek: 1, startTime: '08:00', endTime: '22:00' },
      { dayOfWeek: 2, startTime: '08:00', endTime: '22:00' },
      { dayOfWeek: 3, startTime: '08:00', endTime: '22:00' },
      { dayOfWeek: 4, startTime: '08:00', endTime: '22:00' },
      { dayOfWeek: 5, startTime: '08:00', endTime: '23:00' },
      { dayOfWeek: 6, startTime: '10:00', endTime: '23:00' },
    ],
    rating: 4.8,
    reviewCount: 32,
    imageUrl: 'https://picsum.photos/seed/charger1/400/300',
  },
  {
    id: 'charger-2',
    hostId: 'user-2',
    name: 'Punto de Carga Providencia',
    address: 'Av. Providencia 2000, Providencia, Santiago',
    lat: -33.42,
    lng: -70.60,
    chargerType: ChargerType.Type2,
    pricePerHour: 4000,
    availability: [
      { dayOfWeek: 1, startTime: '09:00', endTime: '20:00' },
      { dayOfWeek: 2, startTime: '09:00', endTime: '20:00' },
      { dayOfWeek: 3, startTime: '09:00', endTime: '20:00' },
      { dayOfWeek: 4, startTime: '09:00', endTime: '20:00' },
      { dayOfWeek: 5, startTime: '09:00', endTime: '20:00' },
    ],
    rating: 4.5,
    reviewCount: 15,
    imageUrl: 'https://picsum.photos/seed/charger2/400/300',
  },
  {
    id: 'charger-3',
    hostId: 'user-3',
    name: 'Carga Nocturna Ñuñoa',
    address: 'Calle Irarrázaval 3500, Ñuñoa, Santiago',
    lat: -33.45,
    lng: -70.61,
    chargerType: ChargerType.Type1,
    pricePerHour: 3000,
    availability: [
        { dayOfWeek: 0, startTime: '18:00', endTime: '08:00' },
        { dayOfWeek: 1, startTime: '18:00', endTime: '08:00' },
        { dayOfWeek: 2, startTime: '18:00', endTime: '08:00' },
        { dayOfWeek: 3, startTime: '18:00', endTime: '08:00' },
        { dayOfWeek: 4, startTime: '18:00', endTime: '08:00' },
        { dayOfWeek: 5, startTime: '18:00', endTime: '08:00' },
        { dayOfWeek: 6, startTime: '18:00', endTime: '08:00' },
    ],
    rating: 4.9,
    reviewCount: 45,
    imageUrl: 'https://picsum.photos/seed/charger3/400/300',
  },
  {
    id: 'charger-4',
    hostId: 'user-1',
    name: 'Mi Segundo Cargador',
    address: 'Calle Falsa 123, Las Condes, Santiago',
    lat: -33.416,
    lng: -70.572,
    chargerType: ChargerType.Type2,
    pricePerHour: 4200,
    availability: [
      { dayOfWeek: 1, startTime: '00:00', endTime: '23:59' },
      { dayOfWeek: 2, startTime: '00:00', endTime: '23:59' },
      { dayOfWeek: 3, startTime: '00:00', endTime: '23:59' },
    ],
    rating: 5.0,
    reviewCount: 5,
    imageUrl: 'https://picsum.photos/seed/charger4/400/300',
  },
];

export const mockBookings: Booking[] = [
  {
    id: 'booking-1',
    userId: 'user-1',
    chargerId: 'charger-2',
    startTime: new Date(new Date().setDate(new Date().getDate() - 5)),
    endTime: new Date(new Date().setDate(new Date().getDate() - 5) + (2 * 60 * 60 * 1000)),
    status: BookingStatus.Completed,
    totalCost: 8000,
  },
  {
    id: 'booking-2',
    userId: 'user-1',
    chargerId: 'charger-3',
    startTime: new Date(new Date().setDate(new Date().getDate() + 2)),
    endTime: new Date(new Date().setDate(new Date().getDate() + 2) + (3 * 60 * 60 * 1000)),
    status: BookingStatus.Confirmed,
    totalCost: 9000,
  },
  {
    id: 'booking-3',
    userId: 'user-2',
    chargerId: 'charger-1',
    startTime: new Date(new Date().setDate(new Date().getDate() - 1)),
    endTime: new Date(new Date().setDate(new Date().getDate() - 1) + (1 * 60 * 60 * 1000)),
    status: BookingStatus.Completed,
    totalCost: 5500,
  },
];
